# [作業目標]
- 仿造範例的 One Hot Encoding, 將指定的資料進行編碼

# [作業重點]
- 將 sub_train 進行 One Hot Encoding 編碼 (In[4], Out[4])

In [2]:
import os
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder


In [3]:
# 設定 data_path, 並讀取 app_train
dir_data = './data/'
f_app_train = os.path.join(dir_data, 'application_train.csv')
app_train = pd.read_csv(f_app_train)

## 作業
將下列部分資料片段 sub_train 使用 One Hot encoding, 並觀察轉換前後的欄位數量 (使用 shape) 與欄位名稱 (使用 head) 變化

In [4]:
sub_train = pd.DataFrame(app_train['WEEKDAY_APPR_PROCESS_START'])
print(sub_train.shape)
sub_train.head()

(307511, 1)


WEEKDAY_APPR_PROCESS_START
0                  WEDNESDAY
1                     MONDAY
2                     MONDAY
3                  WEDNESDAY
4                   THURSDAY

In [5]:
"""
Your Code Here
"""
sub_train.head() 


WEEKDAY_APPR_PROCESS_START
0                  WEDNESDAY
1                     MONDAY
2                     MONDAY
3                  WEDNESDAY
4                   THURSDAY

In [6]:
sub_train.dtypes.value_counts()

object    1
dtype: int64

In [7]:
# Create a label encoder object
le = LabelEncoder()
le_count = 0

# Iterate through the columns
for col in sub_train:
    if sub_train[col].dtype == 'object':
        # If 2 or fewer unique categories
       # if len(list(sub_train[col].unique())) <= 2:
            # Train on the training data
            le.fit(sub_train[col])
            # Transform both training and testing data
            sub_train[col] = le.transform(sub_train[col]) 
            
            # Keep track of how many columns were label encoded
            le_count += 1
            
print('%d columns were label encoded.' % le_count)

1 columns were label encoded.


In [8]:
print(sub_train.head(20))
sub_train.dtypes.value_counts()


    WEEKDAY_APPR_PROCESS_START
0                            6
1                            1
2                            1
3                            6
4                            4
5                            6
6                            3
7                            1
8                            6
9                            4
10                           2
11                           0
12                           0
13                           4
14                           1
15                           2
16                           4
17                           1
18                           0
19                           1


int64    1
dtype: int64

In [9]:
newapp_train = pd.get_dummies(app_train)


In [10]:
print("OLD:"+str(app_train.shape[0])+":"+str(app_train.shape[1])+"\r\nNEW:"+str(newapp_train.shape[0])+":"+str(newapp_train.shape[1]))


OLD:307511:122
NEW:307511:246


In [11]:
print(app_train['CODE_GENDER'].head())

 
print(newapp_train['CODE_GENDER_F'].head())
print(newapp_train['CODE_GENDER_M'].head()) 

0    M
1    F
2    M
3    F
4    M
Name: CODE_GENDER, dtype: object
0    0
1    1
2    0
3    1
4    0
Name: CODE_GENDER_F, dtype: uint8
0    1
1    0
2    1
3    0
4    1
Name: CODE_GENDER_M, dtype: uint8


In [12]:
onehotencoder = OneHotEncoder(categorical_features = [0])

In [13]:
sub_train['WEEKDAY_APPR_PROCESS_START']
X = onehotencoder.fit_transform(sub_train).toarray()


In [14]:
print(sub_train.head())
print(X) 


   WEEKDAY_APPR_PROCESS_START
0                           6
1                           1
2                           1
3                           6
4                           4
[[0. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 0.]]


In [16]:
sub_train = pd.DataFrame(app_train['WEEKDAY_APPR_PROCESS_START'])
oneHotEncoding = pd.get_dummies(sub_train['WEEKDAY_APPR_PROCESS_START'])
print(oneHotEncoding.shape)
oneHotEncoding.head()

(307511, 7)


FRIDAY  MONDAY  SATURDAY  SUNDAY  THURSDAY  TUESDAY  WEDNESDAY
0       0       0         0       0         0        0          1
1       0       1         0       0         0        0          0
2       0       1         0       0         0        0          0
3       0       0         0       0         0        0          1
4       0       0         0       0         1        0          0